# Generated by Django 4.2.7 on 2023-11-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'masculino'), ('f', 'femenino')], default='m', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schedule_start', models.TimeField()),
                ('schedule_end', models.TimeField()),
                ('price', models.IntegerField()),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veterinary')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veterinary')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='owners',
            field=models.ManyToManyField(to='api.owner'),
        ),
        migrations.AddField(
            model_name='animal',
            name='services',
            field=models.ManyToManyField(blank=True, through='api.OS', to='api.service'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccines',
            field=models.ManyToManyField(blank=True, to='api.vaccine'),
        ),
    ]
